name: license-finder base image build

on:
  push:
    paths:
    - dev-sec-ops/base-images/license-finder.dockerfile

jobs:
  build-license-finder-image:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: base image build
        run: docker build -t ${{ vars.DOCKER_HUB_NAME }}/license-finder:latest -f dev-sec-ops/base-images/license-finder.dockerfile .

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: base image push
        run: docker push ${{ vars.DOCKER_HUB_NAME }}/license-finder:latest

